#! /bin/bash

echo "Deleting old directory..."
[ -d "$HOME/.config/base16-shell" ] && rm -rf "$HOME/.config/base16-shell"

git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
