#! /bin/bash

for d in */; do
	# Go into directory
	cd "$d"

	# If the directory contains any executable add it to path
	if [ -d bin ]; then
    PATH=$PATH:$(pwd)/$d/bin
	fi

	# Run the login commands
	if [ -x dot-login ]; then
		. ./dot-login
	fi

	# Return
	cd ../
done
