[admiral]
items = ["left", "arch", "workspaces",
         "center", "title",
         "right", "cmus", "volume", "clock"]

[arch]
path = "./scripts/arch"
static = true

[workspaces]
path = "./scripts/workspaces"

[title]
path = "./scripts/title"

[cmus]
path = "./scripts/cmus"

[volume]
path = "./scripts/volume"

[clock]
path = "./scripts/clock"
reload = 1

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
