[admiral]
items = ["left", "padding", "workspaces",
         "center", "title",
         "right", "cmus", "volume", "clock", "padding"]

[workspaces]
path = "./scripts/workspaces.sh"

[title]
path = "./scripts/title.sh"

[cmus]
path = "./scripts/cmus.sh"

[volume]
path = "./scripts/volume.sh"

[clock]
path = "./scripts/clock.sh"
reload = 1

[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[padding]
path = "echo '  '"
static = true
