#! /bin/bash

mkdir --parents ~/.vim/{autoload,bundle,syntax}
ln -sfrv ./vimrc ~/.vim/vimrc
ln -sfrv ./autoload/pathogen.vim ~/.vim/autoload/pathogen.vim
ln -sfrv ./bundle/install.bat ~/.vim/bundle/install.bat
ln -sfrv ./bundle/plugins.txt ~/.vim/bundle/plugins.txt
ln -sfrv ./bundle/plugman.sh ~/.vim/bundle/plugman.sh
ln -sfrv ./bundle/update.bat ~/.vim/bundle/update.bat
ln -sfrv ./syntax/jflex.vim ~/.vim/syntax/jflex.vim
