#!/bin/bash
# This script contains the list of packages used during installation.

# ----------------
# Minimal Gnome
# ----------------

cat <<EOT
gnome-shell
gnome-core
EOT

# Most hand-picked from the group 'gnome'
cat <<EOT
network-manager-gnome
file-roller
gedit
gnome-clocks
gnome-color-manager
gnome-nettool
gnome-sound-recorder
gnome-tweak-tool
nautilus-sendto
transmission-gtk
xdg-user-dirs-gtk
gstreamer1.0-libav
gstreamer1.0-plugins-ugly
EOT

# Relevant to DE
cat <<EOT
network-manager-openvpn-gnome
dmz-cursor-theme
EOT

# ----------------
# Other apps
# ----------------

cat <<EOT
curl
chromium-browser
EOT

# ----------------
# Development
# ----------------

cat <<EOT
build-essential
exuberant-ctags
git
rxvt-unicode-256color
silversearcher-ag
fonts-inconsolata
vim-nox
python3-venv
EOT
