#! /bin/sh

##################
# BSPWM configuration
##################

panel &

bspc config border_width        1
bspc config window_gap         10


bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV

# bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chrome desktop=^2
bspc rule -a feh floating=on
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#
# Colors
#


bspc config focused_border_color $COLOR_3
bspc config active_border_color $COLOR_15
bspc config normal_border_color $COLOR_7
bspc config presel_border_color $COLOR_4
# locked colors
# sticky colors
bspc config urgent_border_color $COLOR_9
