#! /bin/sh

. ~/.config/colors/colorscheme.sh

##################
# BSPWM configuration
##################

panel &

bspc config border_width       2
bspc config window_gap         8

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config history_aware_focus true

bspc monitor -d One Two Three Four Five Six Seven Eight

# bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a feh state=floating
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#
# Mouse
#

bspc config click_to_focus true

#
# Colors
#

bspc config focused_border_color $COLOR_LYELLOW
bspc config active_border_color $COLOR_WHITE
bspc config normal_border_color $COLOR_DARKGRAY
# locked colors
# sticky colors
# private colors
bspc config urgent_border_color $COLOR_LRED
