#! /bin/sh

# reads colorscheme.
# . ~/.config/colors/colorscheme.sh

# starts apps tied to bspwm.
sxhkd &
[[ $(hostname) == "adaline" ]] && polybar adaline &
[[ $(hostname) == "ada" ]] && polybar ada &
dunst &

# bspwm configuration.
for monitor in $(bspc query -M); do
    bspc monitor $monitor -d One Two Three Four Five Six
done

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

# rules.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating

# colors.
# following tomorrow-night theme: https://github.com/chriskempson/tomorrow-theme
bspc config normal_border_color \#282a2e
bspc config active_border_color \#373b41
bspc config focused_border_color \#f0c674
bspc config presel_feedback_color \#f0c674
