xrdb ~/.Xresources

# Reload font database
xset +fp /usr/share/fonts/local
xset fp rehash

# Cursor
xsetroot -cursor_name left_ptr &

# Screen
compton --config ~/.config/compton.conf -b
feh --bg-scale ~/Pictures/Wallpapers/wallpaper.jpg &
redshift &

# Pulseaudio
pulseaudio --start

# WM
sxhkd -f 100 &
exec bspwm
