xrdb ~/.Xresources

# Cursor
xsetroot -cursor_name left_ptr &

# Screen
compton --config ~/.config/compton.conf -b
feh --bg-scale ~/Pictures/Wallpapers/wallpaper.jpg &
redshift -l 7.9972821:-71.9181585 &

# Pulseaudio
pulseaudio --start

# WM
sxhkd &
exec bspwm
