COLOR_BLACK=$COLOR_0
COLOR_DARKGRAY=$COLOR_8

COLOR_RED=$COLOR_1
COLOR_LRED=$COLOR_9

COLOR_GREEN=$COLOR_2
COLOR_LGREEN=$COLOR_10

COLOR_YELLOW=$COLOR_3
COLOR_LYELLOW=$COLOR_11

COLOR_BLUE=$COLOR_4
COLOR_LBLUE=$COLOR_12

COLOR_MAGENTA=$COLOR_5
COLOR_LMAGENTA=$COLOR_13

COLOR_CYAN=$COLOR_6
COLOR_LCYAN=$COLOR_14

COLOR_GRAY=$COLOR_7
COLOR_WHITE=$COLOR_15
