xrdb ~/.Xresources

# Reload font database
xset +fp /usr/share/fonts/local
xset fp rehash

# Cursor
xsetroot -cursor_name left_ptr &

# Screen
compton --config ~/.config/compton.conf -b
feh --bg-scale --randomize ~/Pictures/Wallpapers/feh/* &
redshift &

# Pulseaudio
#pulseaudio --start

# Touchpad
. ~/.dotfiles/xorg/bin/touchpad-setup

# Exports interfaces
. ~/.dotfiles/xorg/bin/export-interfaces

# WM
exec bspwm
