# load .Xresources
xrdb ~/.Xresources

# disable bell
xset -b

# reload font database
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/TTF
xset fp rehash

# cursor
xsetroot -cursor_name left_ptr &

# screen
compton --config ~/.config/compton.conf -b
feh --bg-scale --randomize ~/Pictures/Wallpapers/feh/* &
redshift &

# pulseaudio
#pulseaudio --start

# Touchpad
. ~/.dotfiles/xorg/bin/touchpad-setup

# exports network interfaces
. ~/.dotfiles/xorg/bin/export-interfaces

# window manager
exec bspwm
