#! /bin/bash
# See: https://ngzhian.wordpress.com/2013/01/11/what-i-learned-about-fonts/
# for information about font

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
# PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
PANEL_FONT_FAMILY="-*-dejavu sans mono-medium-r-normal-*-11-*-*-*-m-*-iso10646-1"
PANEL_ALPHA=0.75
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY PANEL_ALPHA
