#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Export
EDITOR=vim

XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
__GL_SHADER_DISK_CACHE_PATH=$HOME/.cache/nv

export EDITOR XDG_CACHE_HOME XDG_CONFIG_HOME __GL_SHADER_DISK_CACHE_PATH

#
# Path
#

PATH="$PATH:~/.cabal/bin"
PATH="$PATH:~/.cargo/bin"
PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"

export PATH

# Java apps font redering and corrent behaviour in tiling wms.
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
#export _JAVA_AWT_WM_NONREPARENTING=1
