#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias kus='setxkbmap -layout us'
alias kintl='setxkbmap -layout us -variant intl'
alias ghc='ghc -outputdir "out"'
alias npm-exec='PAHT=$(npm bin):$PATH'

# PS1='[\u@\h \W]\$ '

# Arrow codes
# \u00bb
# \u276d
# \u276f
# \u2771

PS1=$'\[\e[01;34m\]\u \[\e[01;1m\]\[\e[01;30m\]\W \[\e[01;31m\]\u00bb\[\e[01;0m\] '
